name: financial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - beautifulsoup4
  - requests
  - pydantic
  - pip
  - pip:
      - fastapi
      - uvicorn
      - rank-bm25
